'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface Player {
  rank: number;
  username: string;
  level: number;
  power: number;
  earnings: string;
  avatar: string;
}

interface GameStats {
  totalPlayers: string;
  dailyRewards: string;
  seasonPrize: string;
  yourRank: number;
}

export default function GameFiPlatformUI() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [loading, setLoading] = useState(true);

  const gameStats: GameStats = {
    totalPlayers: '45,234',
    dailyRewards: '12,500 GAME',
    seasonPrize: '$50K',
    yourRank: 127
  };

  const topPlayers: Player[] = [
    { rank: 1, username: 'DragonSlayer99', level: 85, power: 9850, earnings: '2,450 GAME', avatar: '🐉' },
    { rank: 2, username: 'CryptoKnight', level: 82, power: 9340, earnings: '2,100 GAME', avatar: '⚔️' },
    { rank: 3, username: 'NFTHunter', level: 79, power: 8920, earnings: '1,890 GAME', avatar: '🏹' },
    { rank: 4, username: 'EthWarrior', level: 76, power: 8650, earnings: '1,680 GAME', avatar: '🛡️' },
    { rank: 5, username: 'BlockMage', level: 74, power: 8320, earnings: '1,520 GAME', avatar: '🔮' }
  ];

  useEffect(() => {
    setTimeout(() => setLoading(false), 1500);
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-purple-500 mx-auto mb-4"></div>
          <p className="text-white text-lg">Loading GameFi platform...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-purple-950 to-slate-950">
      {/* Header */}
      <header className="border-b border-slate-700 bg-slate-900/50 backdrop-blur-sm">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <h1 className="text-2xl font-bold text-white">🎮 GameFi Platform</h1>
              <span className="text-sm text-slate-400">Generated by VibeForge</span>
            </div>
            <div className="flex items-center space-x-4">
              <a href="/" className="text-slate-400 hover:text-white transition-colors text-sm">
                ← Back to Generator
              </a>
              <button className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white px-6 py-2 rounded-lg font-medium transition-all transform hover:scale-105">
                Connect Wallet
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Game Stats Banner */}
      <div className="bg-slate-800/30 border-b border-slate-700">
        <div className="container mx-auto px-6 py-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Total Players</h3>
                <div className="text-3xl font-bold text-purple-400">{gameStats.totalPlayers}</div>
                <div className="text-xs text-slate-400 mt-1">Active warriors</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Daily Rewards</h3>
                <div className="text-3xl font-bold text-green-400">{gameStats.dailyRewards}</div>
                <div className="text-xs text-slate-400 mt-1">Distributed today</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Season Prize</h3>
                <div className="text-3xl font-bold text-yellow-400">{gameStats.seasonPrize}</div>
                <div className="text-xs text-slate-400 mt-1">Top 100 players</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Your Rank</h3>
                <div className="text-3xl font-bold text-orange-400">#{gameStats.yourRank}</div>
                <div className="text-xs text-slate-400 mt-1">Global leaderboard</div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-6 py-8">
        {/* Tabs */}
        <div className="flex space-x-1 bg-slate-800/50 rounded-xl p-1 mb-8 max-w-2xl mx-auto">
          {['dashboard', 'inventory', 'battle', 'marketplace', 'tournaments'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`flex-1 py-2 px-3 rounded-lg text-sm font-medium transition-all capitalize ${
                activeTab === tab
                  ? 'bg-purple-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Content */}
        <AnimatePresence mode="wait">
          {activeTab === 'dashboard' && (
            <motion.div
              key="dashboard"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="grid grid-cols-1 lg:grid-cols-3 gap-8"
            >
              {/* Player Profile */}
              <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                <h2 className="text-xl font-bold text-white mb-6">🏆 Your Character</h2>
                
                <div className="text-center mb-6">
                  <div className="w-24 h-24 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full mx-auto mb-4 flex items-center justify-center text-4xl">
                    ⚔️
                  </div>
                  <h3 className="text-xl font-bold text-white">CryptoWarrior</h3>
                  <p className="text-slate-400">Level 42 Paladin</p>
                </div>

                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-slate-400">Experience</span>
                    <span className="text-purple-400 font-medium">8,450 / 10,000 XP</span>
                  </div>
                  <div className="w-full bg-slate-700 rounded-full h-2">
                    <div className="bg-gradient-to-r from-purple-500 to-pink-500 h-2 rounded-full" style={{width: '84.5%'}}></div>
                  </div>

                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                      <div className="text-red-400 font-bold text-lg">2,850</div>
                      <div className="text-slate-400">Attack Power</div>
                    </div>
                    <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                      <div className="text-blue-400 font-bold text-lg">1,920</div>
                      <div className="text-slate-400">Defense</div>
                    </div>
                    <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                      <div className="text-green-400 font-bold text-lg">3,240</div>
                      <div className="text-slate-400">Health</div>
                    </div>
                    <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                      <div className="text-yellow-400 font-bold text-lg">1,650</div>
                      <div className="text-slate-400">Mana</div>
                    </div>
                  </div>

                  <button className="w-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white py-3 rounded-lg font-medium transition-all transform hover:scale-105">
                    🎮 Enter Battle
                  </button>
                </div>
              </div>

              {/* Leaderboard */}
              <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                <h2 className="text-xl font-bold text-white mb-6">🏅 Global Leaderboard</h2>
                
                <div className="space-y-3">
                  {topPlayers.map((player, index) => (
                    <motion.div
                      key={player.username}
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.1 }}
                      className={`flex items-center space-x-3 p-3 rounded-lg ${
                        player.rank <= 3 
                          ? 'bg-gradient-to-r from-yellow-900/30 to-orange-900/30 border border-yellow-600/30' 
                          : 'bg-slate-700/30'
                      }`}
                    >
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${
                        player.rank === 1 ? 'bg-yellow-500 text-black' :
                        player.rank === 2 ? 'bg-gray-400 text-black' :
                        player.rank === 3 ? 'bg-orange-600 text-white' :
                        'bg-slate-600 text-white'
                      }`}>
                        {player.rank}
                      </div>
                      <span className="text-2xl">{player.avatar}</span>
                      <div className="flex-1">
                        <div className="text-white font-medium text-sm">{player.username}</div>
                        <div className="text-slate-400 text-xs">Lvl {player.level} • {player.power} PWR</div>
                      </div>
                      <div className="text-right">
                        <div className="text-green-400 font-medium text-sm">{player.earnings}</div>
                        <div className="text-slate-400 text-xs">24h earnings</div>
                      </div>
                    </motion.div>
                  ))}
                </div>

                <div className="mt-6 p-3 bg-purple-900/30 border border-purple-600/30 rounded-lg">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-white font-medium">Your Position</div>
                      <div className="text-slate-400 text-sm">Keep climbing!</div>
                    </div>
                    <div className="text-orange-400 font-bold text-xl">#{gameStats.yourRank}</div>
                  </div>
                </div>
              </div>

              {/* Recent Activities & Rewards */}
              <div className="space-y-6">
                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                  <h2 className="text-xl font-bold text-white mb-4">💰 Today's Earnings</h2>
                  
                  <div className="space-y-3">
                    {[
                      { action: 'Won PvP Battle', reward: '+125 GAME', time: '2 min ago', icon: '⚔️' },
                      { action: 'Completed Quest', reward: '+85 GAME', time: '15 min ago', icon: '📜' },
                      { action: 'Daily Login Bonus', reward: '+50 GAME', time: '1 hour ago', icon: '🎁' },
                      { action: 'Staking Rewards', reward: '+32 GAME', time: '2 hours ago', icon: '💎' }
                    ].map((activity, index) => (
                      <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="flex items-center justify-between p-3 bg-slate-700/30 rounded-lg"
                      >
                        <div className="flex items-center space-x-3">
                          <span className="text-xl">{activity.icon}</span>
                          <div>
                            <div className="text-white text-sm font-medium">{activity.action}</div>
                            <div className="text-slate-400 text-xs">{activity.time}</div>
                          </div>
                        </div>
                        <div className="text-green-400 font-medium text-sm">{activity.reward}</div>
                      </motion.div>
                    ))}
                  </div>

                  <div className="mt-4 p-3 bg-green-900/30 border border-green-600/30 rounded-lg text-center">
                    <div className="text-green-400 font-bold text-lg">+292 GAME</div>
                    <div className="text-slate-400 text-sm">Total earned today</div>
                  </div>
                </div>

                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                  <h2 className="text-xl font-bold text-white mb-4">🎲 Quick Actions</h2>
                  
                  <div className="grid grid-cols-2 gap-3">
                    <button className="bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 text-white py-3 px-4 rounded-lg font-medium transition-all text-sm">
                      ⚔️ Find Battle
                    </button>
                    <button className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white py-3 px-4 rounded-lg font-medium transition-all text-sm">
                      📜 View Quests
                    </button>
                    <button className="bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white py-3 px-4 rounded-lg font-medium transition-all text-sm">
                      🏪 Marketplace
                    </button>
                    <button className="bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white py-3 px-4 rounded-lg font-medium transition-all text-sm">
                      💎 Stake Tokens
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'inventory' && (
            <motion.div
              key="inventory"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="max-w-6xl mx-auto"
            >
              <h2 className="text-2xl font-bold text-white mb-8 text-center">🎒 Your Inventory</h2>
              
              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
                {[
                  { name: 'Legendary Sword', rarity: 'Legendary', power: '+450 ATK', icon: '⚔️', color: 'from-yellow-500 to-orange-500' },
                  { name: 'Dragon Shield', rarity: 'Epic', power: '+320 DEF', icon: '🛡️', color: 'from-purple-500 to-pink-500' },
                  { name: 'Magic Potion', rarity: 'Rare', power: '+200 HP', icon: '🧪', color: 'from-blue-500 to-cyan-500' },
                  { name: 'Fire Spell', rarity: 'Epic', power: '+380 MAG', icon: '🔥', color: 'from-red-500 to-orange-500' },
                  { name: 'Crystal Armor', rarity: 'Legendary', power: '+500 DEF', icon: '💎', color: 'from-cyan-500 to-blue-500' },
                  { name: 'Speed Boots', rarity: 'Rare', power: '+150 SPD', icon: '👢', color: 'from-green-500 to-emerald-500' },
                  { name: 'Mystic Ring', rarity: 'Epic', power: '+250 MANA', icon: '💍', color: 'from-purple-500 to-indigo-500' },
                  { name: 'Ancient Tome', rarity: 'Rare', power: '+200 WIS', icon: '📚', color: 'from-amber-500 to-yellow-500' }
                ].map((item, index) => (
                  <motion.div
                    key={item.name}
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: index * 0.1 }}
                    className="bg-slate-800/50 border border-slate-700 rounded-xl p-4 hover:border-purple-500 transition-all duration-300 cursor-pointer group"
                  >
                    <div className={`w-16 h-16 bg-gradient-to-r ${item.color} rounded-lg mx-auto mb-3 flex items-center justify-center text-2xl group-hover:scale-110 transition-transform`}>
                      {item.icon}
                    </div>
                    <h3 className="text-white font-medium text-sm text-center mb-1">{item.name}</h3>
                    <div className={`text-xs text-center mb-2 ${
                      item.rarity === 'Legendary' ? 'text-yellow-400' :
                      item.rarity === 'Epic' ? 'text-purple-400' :
                      'text-blue-400'
                    }`}>
                      {item.rarity}
                    </div>
                    <div className="text-green-400 text-xs text-center font-medium">{item.power}</div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800 bg-slate-900/30 backdrop-blur-xl mt-12">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between text-sm text-slate-400">
            <div>Built for ETH Dublin 2025 🇮🇪</div>
            <div className="flex items-center space-x-4">
              <span>GameFi Platform</span>
              <span className="text-purple-400">●</span>
              <span>Powered by VibeForge</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
} 
