'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export default function DeFiLendingUI() {
  const [activeTab, setActiveTab] = useState('lend');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1500);
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-500 mx-auto mb-4"></div>
          <p className="text-white text-lg">Loading DeFi protocol...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-blue-950 to-slate-950">
      {/* Header */}
      <header className="border-b border-slate-700 bg-slate-900/50 backdrop-blur-sm">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <h1 className="text-2xl font-bold text-white">🏦 DeFi Lending</h1>
              <span className="text-sm text-slate-400">Generated by VibeCode AI</span>
            </div>
            <div className="flex items-center space-x-4">
              <a href="/" className="text-slate-400 hover:text-white transition-colors text-sm">
                ← Back to Generator
              </a>
              <button className="bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white px-6 py-2 rounded-lg font-medium transition-all transform hover:scale-105">
                Connect Wallet
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Portfolio Overview */}
      <div className="bg-slate-800/30 border-b border-slate-700">
        <div className="container mx-auto px-6 py-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Total Supplied</h3>
                <div className="text-3xl font-bold text-green-400">$12,450</div>
                <div className="text-xs text-slate-400 mt-1">Earning 5.2% APY</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Total Borrowed</h3>
                <div className="text-3xl font-bold text-orange-400">$8,200</div>
                <div className="text-xs text-slate-400 mt-1">Paying 7.8% APR</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Health Factor</h3>
                <div className="text-3xl font-bold text-green-400">2.45</div>
                <div className="text-xs text-slate-400 mt-1">Safe</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Net APY</h3>
                <div className="text-3xl font-bold text-blue-400">2.1%</div>
                <div className="text-xs text-slate-400 mt-1">Annual yield</div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-6 py-8">
        {/* Tabs */}
        <div className="flex space-x-1 bg-slate-800/50 rounded-xl p-1 mb-8 max-w-md">
          {['lend', 'borrow', 'dashboard'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all capitalize ${
                activeTab === tab
                  ? 'bg-blue-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Content */}
        <AnimatePresence mode="wait">
          {activeTab === 'lend' && (
            <motion.div
              key="lend"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="grid grid-cols-1 lg:grid-cols-2 gap-8"
            >
              {/* Lending Pools */}
              <div className="space-y-4">
                <h2 className="text-xl font-bold text-white mb-4">💰 Supply Assets</h2>
                {[
                  { symbol: 'ETH', name: 'Ethereum', apy: '4.2%', balance: '2.5', supplied: '1.2' },
                  { symbol: 'USDC', name: 'USD Coin', apy: '3.8%', balance: '5,000', supplied: '2,500' },
                  { symbol: 'WBTC', name: 'Wrapped Bitcoin', apy: '2.1%', balance: '0.15', supplied: '0.08' },
                ].map((asset, index) => (
                  <motion.div
                    key={asset.symbol}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="bg-slate-800/50 border border-slate-700 rounded-xl p-6"
                  >
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center space-x-3">
                        <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center text-white font-bold">
                          {asset.symbol[0]}
                        </div>
                        <div>
                          <h3 className="text-white font-semibold">{asset.symbol}</h3>
                          <p className="text-xs text-slate-400">{asset.name}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="text-green-400 font-bold">{asset.apy}</div>
                        <div className="text-xs text-slate-400">APY</div>
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4 mb-4 text-sm">
                      <div>
                        <span className="text-slate-400">Wallet Balance:</span>
                        <div className="text-white font-medium">{asset.balance} {asset.symbol}</div>
                      </div>
                      <div>
                        <span className="text-slate-400">Currently Supplied:</span>
                        <div className="text-white font-medium">{asset.supplied} {asset.symbol}</div>
                      </div>
                    </div>

                    <button className="w-full bg-green-600 hover:bg-green-700 text-white py-2 rounded-lg font-medium transition-colors">
                      Supply {asset.symbol}
                    </button>
                  </motion.div>
                ))}
              </div>

              {/* Supply Form */}
              <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 h-fit">
                <h2 className="text-xl font-bold text-white mb-6">Supply ETH</h2>
                
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm text-slate-400 mb-2">Amount to Supply</label>
                    <div className="relative">
                      <input
                        type="text"
                        placeholder="0.0"
                        className="w-full bg-slate-700 border border-slate-600 rounded-lg px-4 py-3 text-white text-xl focus:ring-2 focus:ring-blue-500"
                      />
                      <div className="absolute right-4 top-1/2 transform -translate-y-1/2 flex items-center space-x-2">
                        <span className="text-slate-400 text-sm">ETH</span>
                        <button className="text-blue-400 text-sm hover:text-blue-300">MAX</button>
                      </div>
                    </div>
                    <div className="flex justify-between mt-2 text-sm text-slate-400">
                      <span>≈ $0.00</span>
                      <span>Balance: 2.5 ETH</span>
                    </div>
                  </div>

                  <div className="bg-slate-700/50 rounded-lg p-4 space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-slate-400">Supply APY</span>
                      <span className="text-green-400 font-medium">4.2%</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-400">Collateral Factor</span>
                      <span className="text-white">82.5%</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-400">Liquidation Threshold</span>
                      <span className="text-white">85%</span>
                    </div>
                  </div>

                  <button className="w-full bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white py-3 rounded-lg font-medium transition-all transform hover:scale-105">
                    🔒 Supply ETH
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800 bg-slate-900/30 backdrop-blur-xl mt-12">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between text-sm text-slate-400">
            <div>Built for ETH Dublin 2025 🇮🇪</div>
            <div className="flex items-center space-x-4">
              <span>DeFi Lending Protocol</span>
              <span className="text-blue-400">●</span>
              <span>Powered by VibeCode AI</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
} 