'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface Post {
  id: string;
  author: string;
  avatar: string;
  content: string;
  likes: number;
  comments: number;
  tips: string;
  timestamp: string;
  nftBadge?: string;
}

interface Creator {
  username: string;
  avatar: string;
  followers: string;
  earnings: string;
  badge: string;
  verified: boolean;
}

export default function SocialDAppUI() {
  const [activeTab, setActiveTab] = useState('feed');
  const [loading, setLoading] = useState(true);

  const posts: Post[] = [
    {
      id: '1',
      author: 'cryptoartist.eth',
      avatar: '🎨',
      content: 'Just dropped my latest NFT collection! The intersection of AI and blockchain continues to amaze me. Each piece represents a unique algorithm signature. 🚀',
      likes: 234,
      comments: 45,
      tips: '12.5 ETH',
      timestamp: '2 hours ago',
      nftBadge: 'Verified Creator'
    },
    {
      id: '2',
      author: 'defi_builder',
      avatar: '🏗️',
      content: 'Building the future of decentralized finance, one smart contract at a time. Our new lending protocol just passed audit! 💰',
      likes: 189,
      comments: 32,
      tips: '8.7 ETH',
      timestamp: '4 hours ago'
    },
    {
      id: '3',
      author: 'web3_educator',
      avatar: '📚',
      content: 'Thread: Why Web3 social platforms will change everything 🧵\n\n1/ Traditional social media extracts value from users\n2/ Web3 gives users ownership of their data and content\n3/ Creators earn directly from their audience',
      likes: 567,
      comments: 89,
      tips: '25.3 ETH',
      timestamp: '6 hours ago',
      nftBadge: 'Top Educator'
    }
  ];

  const topCreators: Creator[] = [
    { username: 'vitalik.eth', avatar: '👑', followers: '2.1M', earnings: '450 ETH', badge: 'Ethereum Founder', verified: true },
    { username: 'artblocks', avatar: '🎨', followers: '890K', earnings: '320 ETH', badge: 'Top Artist', verified: true },
    { username: 'defi_alpha', avatar: '📈', followers: '650K', earnings: '280 ETH', badge: 'DeFi Expert', verified: true },
    { username: 'nft_guru', avatar: '🖼️', followers: '420K', earnings: '210 ETH', badge: 'NFT Specialist', verified: true }
  ];

  useEffect(() => {
    setTimeout(() => setLoading(false), 1500);
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-pink-500 mx-auto mb-4"></div>
          <p className="text-white text-lg">Loading social dApp...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-pink-950 to-slate-950">
      {/* Header */}
      <header className="border-b border-slate-700 bg-slate-900/50 backdrop-blur-sm">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <h1 className="text-2xl font-bold text-white">👥 Social dApp</h1>
              <span className="text-sm text-slate-400">Generated by VibeCode AI</span>
            </div>
            <div className="flex items-center space-x-4">
              <a href="/" className="text-slate-400 hover:text-white transition-colors text-sm">
                ← Back to Generator
              </a>
              <button className="bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white px-6 py-2 rounded-lg font-medium transition-all transform hover:scale-105">
                Connect Wallet
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Stats Banner */}
      <div className="bg-slate-800/30 border-b border-slate-700">
        <div className="container mx-auto px-6 py-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Active Users</h3>
                <div className="text-3xl font-bold text-pink-400">1.2M</div>
                <div className="text-xs text-slate-400 mt-1">Daily active</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Creator Earnings</h3>
                <div className="text-3xl font-bold text-green-400">2,450 ETH</div>
                <div className="text-xs text-slate-400 mt-1">This month</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">NFT Profiles</h3>
                <div className="text-3xl font-bold text-purple-400">89K</div>
                <div className="text-xs text-slate-400 mt-1">Verified creators</div>
              </div>
            </motion.div>

            <motion.div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-xl p-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
              <div className="text-center">
                <h3 className="text-lg font-semibold text-white mb-2">Total Tips</h3>
                <div className="text-3xl font-bold text-yellow-400">15.2K ETH</div>
                <div className="text-xs text-slate-400 mt-1">All time</div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-6 py-8">
        {/* Tabs */}
        <div className="flex space-x-1 bg-slate-800/50 rounded-xl p-1 mb-8 max-w-2xl mx-auto">
          {['feed', 'creators', 'monetize', 'communities'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`flex-1 py-3 px-4 rounded-lg text-sm font-medium transition-all capitalize ${
                activeTab === tab
                  ? 'bg-pink-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Content */}
        <AnimatePresence mode="wait">
          {activeTab === 'feed' && (
            <motion.div
              key="feed"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="grid grid-cols-1 lg:grid-cols-4 gap-8"
            >
              {/* Main Feed */}
              <div className="lg:col-span-3 space-y-6">
                {/* Create Post */}
                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                  <div className="flex items-center space-x-4 mb-4">
                    <div className="w-12 h-12 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full flex items-center justify-center text-xl">
                      👤
                    </div>
                    <input
                      type="text"
                      placeholder="What's happening in Web3?"
                      className="flex-1 bg-slate-700 border border-slate-600 rounded-lg px-4 py-3 text-white placeholder-slate-400 focus:ring-2 focus:ring-pink-500"
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex space-x-4">
                      <button className="text-slate-400 hover:text-pink-400 transition-colors">📷 Media</button>
                      <button className="text-slate-400 hover:text-purple-400 transition-colors">🖼️ NFT</button>
                      <button className="text-slate-400 hover:text-blue-400 transition-colors">📊 Poll</button>
                    </div>
                    <button className="bg-gradient-to-r from-pink-500 to-purple-500 text-white px-6 py-2 rounded-lg font-medium">
                      Post
                    </button>
                  </div>
                </div>

                {/* Posts */}
                {posts.map((post, index) => (
                  <motion.div
                    key={post.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 hover:border-pink-500/30 transition-all duration-300"
                  >
                    <div className="flex items-start space-x-4 mb-4">
                      <div className="w-12 h-12 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full flex items-center justify-center text-xl">
                        {post.avatar}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center space-x-2 mb-1">
                          <h3 className="text-white font-semibold">{post.author}</h3>
                          {post.nftBadge && (
                            <span className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-2 py-1 rounded text-xs">
                              {post.nftBadge}
                            </span>
                          )}
                          <span className="text-slate-400 text-sm">• {post.timestamp}</span>
                        </div>
                        <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{post.content}</p>
                      </div>
                    </div>

                    <div className="border-t border-slate-700 pt-4">
                      <div className="flex items-center justify-between">
                        <div className="flex space-x-6">
                          <button className="flex items-center space-x-2 text-slate-400 hover:text-red-400 transition-colors">
                            <span>❤️</span>
                            <span className="text-sm">{post.likes}</span>
                          </button>
                          <button className="flex items-center space-x-2 text-slate-400 hover:text-blue-400 transition-colors">
                            <span>💬</span>
                            <span className="text-sm">{post.comments}</span>
                          </button>
                          <button className="flex items-center space-x-2 text-slate-400 hover:text-green-400 transition-colors">
                            <span>🔄</span>
                            <span className="text-sm">Share</span>
                          </button>
                        </div>
                        <div className="flex items-center space-x-4">
                          <div className="text-green-400 font-medium text-sm">💰 {post.tips} tips</div>
                          <button className="bg-gradient-to-r from-green-500 to-emerald-500 text-white px-4 py-1 rounded-lg text-sm font-medium hover:from-green-600 hover:to-emerald-600 transition-all">
                            Tip Creator
                          </button>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Sidebar */}
              <div className="space-y-6">
                {/* Top Creators */}
                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                  <h2 className="text-xl font-bold text-white mb-4">🌟 Top Creators</h2>
                  
                  <div className="space-y-3">
                    {topCreators.map((creator, index) => (
                      <motion.div
                        key={creator.username}
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="flex items-center space-x-3 p-3 bg-slate-700/30 rounded-lg hover:bg-slate-700/50 transition-colors cursor-pointer"
                      >
                        <div className="w-10 h-10 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full flex items-center justify-center">
                          {creator.avatar}
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center space-x-1">
                            <h3 className="text-white font-medium text-sm">{creator.username}</h3>
                            {creator.verified && <span className="text-blue-400">✓</span>}
                          </div>
                          <p className="text-slate-400 text-xs">{creator.followers} followers</p>
                        </div>
                        <div className="text-right">
                          <div className="text-green-400 font-medium text-xs">{creator.earnings}</div>
                          <div className="text-slate-400 text-xs">earned</div>
                        </div>
                      </motion.div>
                    ))}
                  </div>

                  <button className="w-full mt-4 bg-gradient-to-r from-pink-500 to-purple-500 text-white py-2 rounded-lg font-medium text-sm">
                    View All Creators
                  </button>
                </div>

                {/* Trending Topics */}
                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                  <h2 className="text-xl font-bold text-white mb-4">🔥 Trending</h2>
                  
                  <div className="space-y-3">
                    {[
                      { topic: '#ETHDublin2025', posts: '12.5K posts' },
                      { topic: '#DeFiSummer', posts: '8.9K posts' },
                      { topic: '#NFTArt', posts: '6.7K posts' },
                      { topic: '#Web3Social', posts: '4.2K posts' },
                      { topic: '#DAOGovernance', posts: '3.8K posts' }
                    ].map((trending, index) => (
                      <motion.div
                        key={trending.topic}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="p-3 bg-slate-700/30 rounded-lg hover:bg-slate-700/50 transition-colors cursor-pointer"
                      >
                        <h3 className="text-pink-400 font-medium text-sm">{trending.topic}</h3>
                        <p className="text-slate-400 text-xs">{trending.posts}</p>
                      </motion.div>
                    ))}
                  </div>
                </div>

                {/* Creator Tools */}
                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                  <h2 className="text-xl font-bold text-white mb-4">🛠️ Creator Tools</h2>
                  
                  <div className="space-y-3">
                    <button className="w-full bg-gradient-to-r from-purple-600 to-purple-700 text-white py-2 rounded-lg text-sm">
                      🖼️ Mint NFT Profile
                    </button>
                    <button className="w-full bg-gradient-to-r from-green-600 to-green-700 text-white py-2 rounded-lg text-sm">
                      💰 Monetize Content
                    </button>
                    <button className="w-full bg-gradient-to-r from-blue-600 to-blue-700 text-white py-2 rounded-lg text-sm">
                      📊 Analytics
                    </button>
                    <button className="w-full bg-gradient-to-r from-pink-600 to-pink-700 text-white py-2 rounded-lg text-sm">
                      🎯 Promote Post
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'creators' && (
            <motion.div
              key="creators"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="max-w-6xl mx-auto"
            >
              <h2 className="text-2xl font-bold text-white mb-8 text-center">🌟 Featured Creators</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {topCreators.concat([
                  { username: 'crypto_poet', avatar: '📝', followers: '320K', earnings: '180 ETH', badge: 'Content Creator', verified: true },
                  { username: 'blockchain_dev', avatar: '👨‍💻', followers: '280K', earnings: '150 ETH', badge: 'Tech Expert', verified: true },
                  { username: 'nft_collector', avatar: '🖼️', followers: '190K', earnings: '120 ETH', badge: 'Top Collector', verified: false }
                ]).map((creator, index) => (
                  <motion.div
                    key={creator.username}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 hover:border-pink-500 transition-all duration-300"
                  >
                    <div className="text-center mb-6">
                      <div className="w-20 h-20 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full mx-auto mb-4 flex items-center justify-center text-3xl">
                        {creator.avatar}
                      </div>
                      <div className="flex items-center justify-center space-x-2 mb-2">
                        <h3 className="text-xl font-bold text-white">{creator.username}</h3>
                        {creator.verified && <span className="text-blue-400 text-xl">✓</span>}
                      </div>
                      <p className="text-pink-400 text-sm font-medium">{creator.badge}</p>
                    </div>

                    <div className="grid grid-cols-2 gap-4 mb-6">
                      <div className="text-center">
                        <div className="text-lg font-bold text-white">{creator.followers}</div>
                        <div className="text-slate-400 text-sm">Followers</div>
                      </div>
                      <div className="text-center">
                        <div className="text-lg font-bold text-green-400">{creator.earnings}</div>
                        <div className="text-slate-400 text-sm">Earned</div>
                      </div>
                    </div>

                    <div className="flex space-x-3">
                      <button className="flex-1 bg-gradient-to-r from-pink-500 to-purple-500 text-white py-2 rounded-lg font-medium text-sm">
                        Follow
                      </button>
                      <button className="flex-1 bg-slate-700 text-white py-2 rounded-lg font-medium text-sm hover:bg-slate-600 transition-colors">
                        Tip
                      </button>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800 bg-slate-900/30 backdrop-blur-xl mt-12">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between text-sm text-slate-400">
            <div>Built for ETH Dublin 2025 🇮🇪</div>
            <div className="flex items-center space-x-4">
              <span>Social dApp Platform</span>
              <span className="text-pink-400">●</span>
              <span>Powered by VibeCode AI</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
} 